Repository ant-design/compatible, pull requests merged in 2019-11, with the labels that each got.

#5 feat: update with antd icons
  package.json
  src/icon/utils.ts
  tests/icon/index.test.tsx
Labels: enhancement

#6 fix: less import use tilde `~`
  src/form/style/index.less
  src/form/style/mixin.less
  src/mention/style/index.less
Labels: bug

#7 doc: update readme
  README.md
Labels: doc

#8 doc: use css import in readme
  README.md
Labels: doc

#9 Revert "fix: less import use tilde `~`"
  src/form/style/index.less
  src/form/style/mixin.less
  src/mention/style/index.less
Labels: bug
