Repository ant-design/compatible, pull requests merged in 2020-01, with the labels that each got.

#19 chore: merge antd change
  src/form/style/index.less
Labels: chore

#20 chore: add legacy warning message
  src/_util/upgradeMessage.ts
  src/form/Form.tsx
  src/icon/index.tsx
  src/mention/index.tsx
Labels: chore

#23 fix: form feebback text color
  src/form/style/mixin.less
Labels: bug

#24 feat: update types
  package.json
  src/icon/index.tsx
  tests/icon/__snapshots__/index.test.tsx.snap
  tests/icon/index.test.tsx
  tests/icon/logo.svg
  tests/icon/types.test.tsx
  tests/utils.tsx
  typing.d.ts
Labels: enhancement

#25 build: add publish registry
  package.json
Labels: build
